name: ECR Test CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: eksdemo1
  REPOSITORY_URI: 125137910162.dkr.ecr.us-east-1.amazonaws.com/devops-kube-nginx
  IMAGE_TAG: ${{ github.run_number }} # GitHub run number as a unique image tag

# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  eks-ecr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::125137910162:role/GitHubAction-ECR_RoleWithAction
          role-session-name: ecrrolesessiontemp
          aws-region: ${{ env.AWS_REGION }}

      - name: Set image tag
        run: |
          echo "Setting image tag to ${{ env.IMAGE_TAG }}"
          sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI:$IMAGE_TAG"'@' kube-manifests/01-DEVOPS-Nginx-Deployment.yml

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.REPOSITORY_URI }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }}
      
      - name: Debug kubectl configuration
        run: |
          cat $GITHUB_WORKSPACE/.kube/config
          kubectl config current-context

      - name: Configure kubectl
        run: |
          export KUBECONFIG=$GITHUB_WORKSPACE/.kube/config

      - name: Check kubectl
        run: |
          kubectl version --client
          kubectl config view 

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          kubectl apply -f kube-manifests/ --validate=false
